import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import Header from "@/Components/Header/Header";
import Footer from "@/Components/Footer/Footer";
import { ReduxProvider } from "@/libs/ReduxProvider";
import "react-toastify/dist/ReactToastify.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Basket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased w-full bg-green-500`}
      >
        <ReduxProvider >
          <Header />
          {children}
          <Footer />
          </ReduxProvider>
        <ToastContainer/>
      </body>
    </html>
  );
}
