export interface CreateBrand {
    title:string
    description?:string
    image?:string
    products?:{
        id:string
        slug:string
        title:string
        image?:string
        price:number
        oldPrice?:number
        quantity:number
        gallary?:string[]
        offer?:string    
    }[]
}
export interface UpdateBrand {
    id:string
    title?:string
    description?:string
    image?:string
    products?:{
        id?:string
        slug?:string
        title:string
        image?:string
        price?:number
        oldPrice?:number
        quantity?:number
        gallary?:string[]
        offer?:string
    }[]
}